### PR TITLE
Convert empty values

### PR DESCRIPTION
**Pull request by murtyjones**

### CODE REVIEW

**Review by mckalexee — APPROVED** [review]
LGTM!

**Comment by mckalexee** [comment]
@murtyjones This has been published to `v1.1.1`

**Comment by murtyjones** [comment]
@mckalexee cheers mate. now get back to vacation!

**Comment by mckalexee** [comment]
> @mckalexee cheers mate. now get back to vacation!

I'm on vacation! This isn't a work thing. This is our open source project.

**Pull request merged**
